export const mockData = [
  {
    adult: false,
    backdrop_path: '/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg',
    genre_ids: [28, 35],
    id: 897087,
    original_language: 'en',
    original_title: 'Freelance',
    overview: '',
    popularity: 2367.027,
    poster_path: '/zDb5YeHSGGMlS6eqhUXcVU2OzAJ.jpg',
    release_date: '2023-10-05',
    title: '프리랜스',
    video: false,
    vote_average: 6.438,
    vote_count: 193
  },
  {
    adult: false,
    backdrop_path: '/1X7vow16X7CnCoexXh4H4F2yDJv.jpg',
    genre_ids: [80, 18, 36],
    id: 466420,
    original_language: 'en',
    original_title: 'Killers of the Flower Moon',
    overview:
      '1920년대 오클라호마주 오세이지 부족 땅에서 석유가 발견된 후, 부족 사람들이 한 명씩 죽어 나가자 FBI가 미스터리를 풀기 위해 나선다.',
    popularity: 1806.389,
    poster_path: '/6jByCqeQXEu3RR5qvlTCBamJQED.jpg',
    release_date: '2023-10-18',
    title: '플라워 킬링 문',
    video: false,
    vote_average: 7.702,
    vote_count: 1268
  },
  {
    adult: false,
    backdrop_path: '/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg',
    genre_ids: [16, 10751, 10402, 14, 35],
    id: 901362,
    original_language: 'en',
    original_title: 'Trolls Band Together',
    overview:
      '전 세계 모든 트롤을 열광케 했던 최고의 아이돌 그룹 ‘브로존’. 역대급 무대 실수와 형제 간의 불화로 결국 해체한 뒤, 모두에게 잊혀 간다. 그러던 어느 날, ‘브로존’의 황금막내 ‘브랜치’는 메인보컬 ‘플로이드’가 슈퍼스타 ‘벨벳’과 ‘비니어’에게 잡혀 재능을 빼앗기고 있다는 소식을 듣는다. 그를 구하기 위해서는 흩어져 있는 ‘브로존’을 재결합하고 완벽한 화음을 되찾아야 하는데… 12월, 가장 짜릿한 컴백 무대의 시작!',
    popularity: 1560.713,
    poster_path: '/7M2pc9OboapgtoBbkU49Aim7O5B.jpg',
    release_date: '2023-10-12',
    title: '트롤 밴드 투게더',
    video: false,
    vote_average: 7.2,
    vote_count: 325
  },
  {
    adult: false,
    backdrop_path: '/9PqD3wSIjntyJDBzMNuxuKHwpUD.jpg',
    genre_ids: [16, 35, 10751],
    id: 1075794,
    original_language: 'en',
    original_title: 'Leo',
    overview:
      '초등학교 마지막 해를 보내는 아이들. 이 모습을 교실에서 키우는 반려동물의 눈을 통해 바라본다. 성장 스토리를 담은 뮤지컬 코미디로 애덤 샌들러가 반려동물인 도마뱀의 목소리 연기를 선보인다.',
    popularity: 1303.89,
    poster_path: '/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg',
    release_date: '2023-11-17',
    title: '레오',
    video: false,
    vote_average: 7.559,
    vote_count: 500
  },
  {
    adult: false,
    backdrop_path: '/yOm993lsJyPmBodlYjgpPwBjXP9.jpg',
    genre_ids: [35, 10751, 14],
    id: 787699,
    original_language: 'en',
    original_title: 'Wonka',
    overview:
      '초콜릿 제조가이자 발명가인 윌리 웡카는 세계 최고의 초콜릿 가게를 열기 위해 ‘달콤한 백화점’을 찾지만, 이를 방해하는 초콜릿 연합의 위협을 받게 되는데…',
    popularity: 1256.256,
    poster_path: '/5Afx73NwXPdgHd3Kt1tU7ig4Vox.jpg',
    release_date: '2023-12-06',
    title: '웡카',
    video: false,
    vote_average: 6.984,
    vote_count: 63
  },
  {
    adult: false,
    backdrop_path: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    genre_ids: [18, 36],
    id: 872585,
    original_language: 'en',
    original_title: 'Oppenheimer',
    overview: '세상을 구하기 위해 세상을 파괴할 지도 모르는 선택을 해야 하는 천재 과학자의 핵개발 프로젝트.',
    popularity: 1071.012,
    poster_path: '/kAYtsVpE7q6NhLz6vKYAxOM6LmN.jpg',
    release_date: '2023-07-19',
    title: '오펜하이머',
    video: false,
    vote_average: 8.14,
    vote_count: 5316
  },
  {
    adult: false,
    backdrop_path: '/jhpsTzbXEu5bkCPmBqxv7vUTjIT.jpg',
    genre_ids: [14, 12, 878, 28],
    id: 566810,
    original_language: 'en',
    original_title: 'Dragon Kingdom',
    overview: '',
    popularity: 1184.555,
    poster_path: '/o7StI2iR8yY1N67meSkNcXfojyD.jpg',
    release_date: '2018-11-26',
    title: 'Dragon Kingdom',
    video: false,
    vote_average: 5.348,
    vote_count: 33
  },
  {
    adult: false,
    backdrop_path: '/3xvdNyZ9WsVJpyeGhm85fukeZz4.jpg',
    genre_ids: [878, 9648, 53],
    id: 1001835,
    original_language: 'en',
    original_title: 'Wifelike',
    overview:
      '가까운 미래, 암시장에서 인공 인간을 거래하는 범죄자를 추격하고 있는 형사. 인공인간 착취를 끝내기 위해 형사의 죽은 아내로 위장하여 인공인간으로 잠입한다. 전생의 기억이 떠오르기 시작하면서 그녀는 현실에 의문을 품기 시작하는데...',
    popularity: 905.273,
    poster_path: '/b5EJe2B7JONgFUgKkV4xpxBuz5p.jpg',
    release_date: '2022-08-12',
    title: '와이프라이크',
    video: false,
    vote_average: 7.101,
    vote_count: 188
  },
  {
    adult: false,
    backdrop_path: '/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg',
    genre_ids: [27, 9648],
    id: 507089,
    original_language: 'en',
    original_title: "Five Nights at Freddy's",
    overview:
      "80년대에 아이들이 실종되고 폐업한지 오래된 프레디의 피자가게 그곳의 야간 경비 알바를 하게 된 ‘마이크'는 캄캄한 어둠만이 존재하는 줄 알았던 피자가게에서 살아 움직이는 피자가게 마스코트 '프레디와 친구들’을 목격한다. 어딘가 기괴하고 섬뜩한 프레디와 친구들이 실체를 드러내기 시작하는데...",
    popularity: 880.311,
    poster_path: '/6rUZcazlkYILiNPKFgCGkzTn0BN.jpg',
    release_date: '2023-10-25',
    title: '프레디의 피자가게',
    video: false,
    vote_average: 7.8,
    vote_count: 2740
  },
  {
    adult: false,
    backdrop_path: '/mIpdOcss3oedSYB8juiSXg89uLL.jpg',
    genre_ids: [28, 878, 12, 53],
    id: 479753,
    original_language: 'en',
    original_title: 'Shockwave: Countdown to Disaster',
    overview:
      '지질학자 케이트를 인질로 잡은 테러리스트들이 지각을 변동시킬 수 있는 헬스톰을 작동시킨다. 세계 곳곳에서 대지진과 폭풍이 발생하고 파리, 런던, 베이징, LA등 대도시가 초토화된다. 케이트는 재난을 멈추려 지질을 측정하고 국방부에 핵무기를 사용할 것을 요청하지만, 최후의 지각변동이 시작되는데…',
    popularity: 1049.257,
    poster_path: '/r6X7YzhoQskBpeKd7qeYPlVaVvZ.jpg',
    release_date: '2017-09-02',
    title: '카운트다운: 쇼크웨이브',
    video: false,
    vote_average: 5.577,
    vote_count: 52
  },
  {
    adult: false,
    backdrop_path: '/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg',
    genre_ids: [28, 12, 18],
    id: 670292,
    original_language: 'en',
    original_title: 'The Creator',
    overview:
      "인류를 지키기 위해 만들어진 AI가 LA에 핵폭탄을 터뜨린 후, 인류와 AI 간의 피할 수 없는 전쟁이 시작된다. 전직 특수부대 요원 ‘조슈아’는 실종된 아내의 단서를 얻을지도 모른다는 생각에 전쟁을 끝내기 위한 인류의 작전에 합류한다. 인류를 위협할 강력한 무기와 이를 창조한 ‘창조자’를 찾아 나서고, 그 무기가 아이 모습의 AI 로봇 '알피'란 사실을 알게 되는데… 인간적인가, 인간의 적인가? 10월, SF 블록버스터의 신세계가 펼쳐진다!",
    popularity: 852.508,
    poster_path: '/vFsSluuzqxR46Ils9ib52ItdE9u.jpg',
    release_date: '2023-09-27',
    title: '크리에이터',
    video: false,
    vote_average: 7.121,
    vote_count: 1379
  },
  {
    adult: false,
    backdrop_path: '/4MUfDtBqUFqotGF5RJOfNfoBTLo.jpg',
    genre_ids: [28, 27, 14],
    id: 951546,
    original_language: 'en',
    original_title: 'Reign of Chaos',
    overview: '',
    popularity: 869.204,
    poster_path: '/nTMmpvR9TyV631tpFr4FtYxG0FC.jpg',
    release_date: '2022-04-12',
    title: 'Reign of Chaos',
    video: false,
    vote_average: 5.545,
    vote_count: 23
  },
  {
    adult: false,
    backdrop_path: '/8GnWDLn2AhnmkQ7hlQ9NJUYobSS.jpg',
    genre_ids: [28, 10749, 18],
    id: 695721,
    original_language: 'en',
    original_title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
    overview:
      '반란의 불씨를 잠재우기 위해 시작된 잔인한 서바이벌 헝거게임. 헝거게임 10회를 맞아 ‘멘토제’가 도입되고 ‘스노우’는 12구역의 소녀 ‘루시 그레이’의 멘토가 된다. 그는 몰락한 가문의 영광을 되찾기 위해 ‘루시 그레이’를 헝거게임에서 우승 시키려 수단과 방법을 가리지 않는데…',
    popularity: 722.276,
    poster_path: '/9f9YsmXoy9ghqZKIVuKHkmGGZCY.jpg',
    release_date: '2023-11-15',
    title: '헝거게임: 노래하는 새와 뱀의 발라드',
    video: false,
    vote_average: 7.294,
    vote_count: 645
  },
  {
    adult: false,
    backdrop_path: '/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg',
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: 'en',
    original_title: 'Fast X',
    overview:
      '돔과 그의 패밀리 앞에 나타난 운명의 적 단테. 과거의 그림자는 돔의 모든 것을 파괴하기 위해 달려온다. 단테에 의해 산산히 흩어진 패밀리들은 모두 목숨을 걸고 맞서야 하는 함정에 빠지고 마는데...',
    popularity: 794.03,
    poster_path: '/wXNihLltMCGR7XepN39syIlCt5X.jpg',
    release_date: '2023-05-17',
    title: '분노의 질주: 라이드 오어 다이',
    video: false,
    vote_average: 7.198,
    vote_count: 4428
  },
  {
    adult: false,
    backdrop_path: '/oqbcmZJJ1EWkOPiGjqABaUN18rI.jpg',
    genre_ids: [16, 35, 10751],
    id: 1046032,
    original_language: 'en',
    original_title: 'The Bad Guys: A Very Bad Holiday',
    overview:
      '올해도 어김없이 ‘크리스마스 도둑질 쇼’를 즐기려는 울프와 무법자 동물들. 그런데 그러려면 도시 전체의 크리스마스 분위기부터 되살려야 한다. 그것도 한시바삐!',
    popularity: 674.721,
    poster_path: '/oc2Zz5JS6OgukkLoBSXUPggg30i.jpg',
    release_date: '2023-11-30',
    title: '배드 가이즈: 최악의 크리스마스',
    video: false,
    vote_average: 6.071,
    vote_count: 28
  },
  {
    adult: false,
    backdrop_path: '/ixhr0YVs0Du0fPIYQSYYOIf3j0R.jpg',
    genre_ids: [878, 28],
    id: 854648,
    original_language: 'en',
    original_title: 'Robot Apocalypse',
    overview:
      "근미래 최초의 대량 두뇌 인공지능 컴퓨터 '메두사'를 개발해낸 로페즈, 메리에타 박사는 실험을 진행 하던 중 '메두사'가 명령을 벗어난 것을 확인한다. '메두사'가 군사용 로봇군단을 장악해 인류 말살 계획을 실행하는 것을 알아챈 두 박사와 함께 연구원이자 해커들은 인공지능 메두사를 없애고 인류를 구해내야하는데....",
    popularity: 877.365,
    poster_path: '/hULzHYoJRyLmQgMXHh2AwFM83uY.jpg',
    release_date: '2021-07-26',
    title: '로봇 대전쟁: A.I 머신건',
    video: false,
    vote_average: 2.1,
    vote_count: 7
  },
  {
    adult: false,
    backdrop_path: '/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg',
    genre_ids: [878, 12, 28],
    id: 609681,
    original_language: 'en',
    original_title: 'The Marvels',
    overview:
      '강력한 힘으로 은하계를 수호하는 최강 히어로 캡틴 마블 캐럴 댄버스. 캡틴 마블의 오랜 친구의 딸이자, 빛의 파장을 조작하는 히어로 모니카 램보. 최애 히어로 캡틴 마블의 열렬한 팬인 미즈 마블 카말라 칸. 캡틴 마블에 대한 복수를 꿈꾸는 냉혹한 크리족 리더 다르-벤의 영향으로 세 명의 히어로는 능력을 사용할 때마다 서로의 위치가 뒤바뀌게 된다. 뜻하지 않게 우주와 지구를 넘나들게 되는 예측 불가하고 통제 불가한 상황 속, 다르-벤은 지구를 포함해 캡틴 마블이 고향이라고 부르는 수많은 행성을 모두 파멸시키려 하고, 이를 저지하기 위해 모인 팀 마블스는 하나로 힘을 모으는데…',
    popularity: 624.688,
    poster_path: '/qApkjVJzZ2nkFUcFhcYkTBaRnNj.jpg',
    release_date: '2023-11-08',
    title: '더 마블스',
    video: false,
    vote_average: 6.6,
    vote_count: 648
  },
  {
    adult: false,
    backdrop_path: '/iaMIylLoN7Y3CvrA0pg2ZFKjk26.jpg',
    genre_ids: [10752, 18, 28],
    id: 1047925,
    original_language: 'en',
    original_title: 'Come Out Fighting',
    overview: '',
    popularity: 684.519,
    poster_path: '/sERwJxz0sqsbcUoTm66l9pI6HcH.jpg',
    release_date: '2023-05-19',
    title: 'Come Out Fighting',
    video: false,
    vote_average: 5.06,
    vote_count: 25
  },
  {
    adult: false,
    backdrop_path: '/628Dep6AxEtDxjZoGP78TsOxYbK.jpg',
    genre_ids: [28, 53],
    id: 575264,
    original_language: 'en',
    original_title: 'Mission: Impossible - Dead Reckoning Part One',
    overview:
      '모든 인류를 위협할 새로운 무기를 추적하게 된 에단 헌트와 IMF팀은 이 무기가 인류의 미래를 통제할 수 있다는 사실을 알게 된다. 전 세계가 위태로운 상황에 처한 가운데, 이를 추적하던 에단 헌트에게 어둠의 세력까지 접근하고 마침내 미스터리하고 강력한 빌런과 마주하게 된 그는 가장 위험한 작전을 앞두고 자신이 아끼는 사람들의 생명과 중요한 임무 사이에서 선택을 해야 하는 상황에 놓이게 되는데…',
    popularity: 673.339,
    poster_path: '/dIcLgXA6R54EZ0XPSMKW4XDNCAA.jpg',
    release_date: '2023-07-08',
    title: '미션 임파서블: 데드 레코닝 PART ONE',
    video: false,
    vote_average: 7.591,
    vote_count: 2664
  },
  {
    adult: false,
    backdrop_path: '/j9LX1sF7WSXmJlnhf0RGpWzEC0i.jpg',
    genre_ids: [28, 12, 53],
    id: 299054,
    original_language: 'en',
    original_title: 'Expend4bles',
    overview:
      '테러 단체에게 핵미사일이 탈취되어 3차 세계대전이 발발할 위기의 상황에 ‘리’(제이슨 스타뎀)를 새로운 리더로 맞은 무적의 팀 익스펜더블이 작전에 투입되는데...',
    popularity: 724.55,
    poster_path: '/dWR8OTRCcYDbBmd8GKsyJT73kU2.jpg',
    release_date: '2023-09-15',
    title: '익스펜더블 4',
    video: false,
    vote_average: 6.4,
    vote_count: 881
  }
]
